namespace SchoolProfilesDataModel
{
    // Defines the Note entity.
    // The table will be autogenerated based on this.
    public class NoteEntity
    {
        public int Id { get; set; }
        public string Text { get; set; }

        // These two fields are both needed to create the Student relationship.
        public int StudentId { get; set; }
        public StudentEntity Student { get; set; }
    }
}
