using System;
using System.Collections.Generic;

namespace SchoolProfilesDataModel
{
    // Defines the Student entity.
    // The table will be autogenerated based on this.
    public class StudentEntity : ISchoolEntity
    {
        public Guid Id { get; private set; }
        public string Name { get; set; }

        // This field sets up the Notes relationship.
        public List<NoteEntity> Notes { get; set; }

        public StudentEntity()
        {
            this.Id = Guid.NewGuid();
        }

        public List<NoteEntity> AccessNotes(ISchoolEntity agent, StudentEntity subject)
        {
            if (agent.Id == subject.Id)
            {
                return subject.Notes;
            }
            throw new SchoolAccessDeniedException(
                "Access Denied for student " + agent.Id +
                " to view notes for student " + subject.Id);
        }
    }
}
